#!/usr/bin/env python3
"""build_pdf.py — Merge approved docs/ content into a single PDF

What it does:
1. Reads only the files listed in PDF_ALLOWLIST (explicit allowlist — no wildcard scanning).
   modules/*/*-module-data-flow.md files are the only exception: they are added automatically
   because they are created per module during development.
   log-*.md files are intentionally excluded (implementation detail, not suitable for PDF audience).
2. For every .html file in docs/ that has a matching .svg (generated by the diagram scripts),
   embeds the SVG as an image AND adds a clickable link to the original interactive HTML file.
3. Prepends a "How to use this document" page at the start of the PDF.
4. Converts everything to one PDF with a table of contents, page numbers, and working internal links.

PDF section order:
  1. How to Use
  2. Business (why)
  3. Requirements (what)
  4. Architecture (how it is structured)
  5. Specifications (how it is implemented)
  6. Flows (how it runs)
  7. Project Status

Usage:
  python3 docs/script/generators/build_pdf.py [docs_dir] [-o output.pdf] [--lang en|zh] [--project-type TYPE]

  --lang en              Section labels and UI text in English (default)
  --lang zh              Section labels and UI text in Traditional Chinese
  --project-type TYPE    Filter PDF to only include documents relevant to the project type(s).
                         Comma-separate multiple types for hybrid projects:
                           --project-type data-pipeline,web-app
                         Valid values: web-app, cli-tool, library, data-pipeline,
                                       ml-pipeline, microservices, llm-app, iac, mobile-app
                         Omit to include all files that exist (backward-compatible default).
  --content spec|full    Control which chapters are included (default: full).
                           full — all six chapters (Introduction, Plan, Design, Build, Test, Deployment)
                           spec — system specification only: Introduction, Design, Build, Deployment
                                  (omits Plan and Test chapters — suitable for stakeholder handoff)

To add a file to the PDF: set pdf=true and pdf_chapter=<chapter> in document-registry.yaml.
For non-registry scaffold files, add an entry to _STATIC_PDF_ENTRIES in this script.

Requires: pip install markdown weasyprint cairosvg --break-system-packages
"""
import argparse
import glob
import os
import re
import shutil
import subprocess
import sys
import tempfile
import xml.etree.ElementTree as ET
import markdown
from weasyprint import HTML, CSS
import cairosvg
try:
    from PIL import Image
except ImportError:
    print("Error: Pillow is required. Run: pip install Pillow --break-system-packages")
    sys.exit(1)

_script_dir = os.path.dirname(os.path.abspath(__file__))
_validators_dir = os.path.join(os.path.dirname(_script_dir), 'validators')
sys.path.insert(0, _script_dir)
sys.path.insert(0, _validators_dir)
from _registry import build_pdf_entries, load_registry

# ── Project type sets ─────────────────────────────────────────────────────────
_ALL9   = frozenset({"web-app", "cli-tool", "library", "data-pipeline",
                     "ml-pipeline", "microservices", "llm-app", "iac", "mobile-app"})
_ALL    = frozenset({"web-app", "cli-tool", "library", "data-pipeline",
                     "ml-pipeline", "microservices", "llm-app"})
_MOBILE = frozenset({"mobile-app"})

# Non-registry scaffold files always included regardless of project type
_STATIC_PDF_ENTRIES = [
    ("introduction", "project-requirements.md",         _ALL9),
    ("plan",         "project-plan.md",                 _ALL9),
    ("plan",         "changelog.md",                    _ALL9),
    ("build",        "modules/module-data-flow.md",     _ALL | _MOBILE),
    ("build",        "modules/module-flow.md",          _ALL | _MOBILE),
    ("build",        "codebase-map.md",                 _ALL9),
]

_CHAPTER_SORT = {"introduction": 0, "plan": 1, "design": 2, "build": 3, "test": 4, "deployment": 5}


def _build_pdf_allowlist() -> list:
    """Build PDF_ALLOWLIST from static scaffold entries + registry pdf=true entries."""
    registry_entries = build_pdf_entries(load_registry())

    by_chapter: dict[str, list] = {c: [] for c in _CHAPTER_SORT}
    for entry in _STATIC_PDF_ENTRIES:
        by_chapter[entry[0]].append(entry)
    for entry in registry_entries:
        by_chapter[entry[0]].append(entry)

    result = []
    for chapter in sorted(by_chapter, key=lambda c: _CHAPTER_SORT[c]):
        result.extend(by_chapter[chapter])
    return result


PDF_ALLOWLIST = _build_pdf_allowlist()

# ── Per-file section filter ───────────────────────────────────────────────────
PDF_SECTION_FILTER = {
    "modules/module-data-flow.md":  ["## Module Flow Files"],
    "modules/module-flow.md":       ["## Flow Files"],
    "business/business-objects.md": ["## Object Files", "## Relationships"],
    "business/business-process.md": ["## Process Files"],
    "business/business-rules.md":   ["## Approval Rules", "## Validation Rules",
                                     "## Notification Rules", "## Audit Rules"],
    "specs/prompt-library.md":      ["## Active Prompts"],
}

# ── Auto-scan patterns ────────────────────────────────────────────────────────
AUTO_SCAN_TYPES = {
    "modules/*/*-module-data-flow.md": _ALL | _MOBILE,
    "modules/*/*-flow.md":             _ALL | _MOBILE,
    "business/*-process.md":          frozenset({"web-app", "microservices", "cli-tool",
                                                  "data-pipeline"}) | _MOBILE,
    "business/*-object.md":           frozenset({"web-app", "microservices"}),
    "specs/prompts/*-prompt.md":      frozenset({"llm-app"}),
}

# ── PlantUML configuration ────────────────────────────────────────────────────
# Set PLANTUML_JAR to the path of your plantuml.jar file.
# Download from: https://plantuml.com/download
# Can also be set via environment variable: PLANTUML_JAR=/path/to/plantuml.jar
PLANTUML_JAR = os.environ.get(
    'PLANTUML_JAR',
    os.path.join(os.path.dirname(__file__), 'plantuml.jar')
)

# Maps diagram key (HTML filename without extension) → target doc(s) where it should be injected.
# Value can be a str (single doc) or list of str (inject into multiple docs).
# For *-module-data-flow-class diagrams, the target is resolved dynamically in inject_diagrams.
DIAGRAM_TARGETS = {
    # Architecture diagrams
    "architecture":            "architecture/architecture.md",
    "schema":                  "specs/data-model.md",
    # State diagrams
    "data-model-state":        "specs/data-model.md",
    # *-object-state → matched dynamically in inject_diagrams
    # Use case diagram
    "permissions-usecase":     "specs/permissions.md",
    # *-process-activity → matched dynamically in inject_diagrams
    # Component diagrams
    "architecture-component":  "architecture/architecture.md",
    "backend-component":       "architecture/backend.md",
    "frontend-component":      "architecture/frontend.md",
    # "deployment-component": removed — deployment diagram now uses ```plantuml block
    # Page structure component diagram — injected into codebase-map as project overview
    "codebase-map-component":  "codebase-map.md",
    # activity/sequence/*-class are matched dynamically in inject_diagrams
}



# UI strings for each supported language.
# Add a new language by copying the "en" block with a new key.
STRINGS = {
    "en": {
        "pdf_title":     "Project Documentation",
        "toc_heading":   "Table of Contents",
        "diagram_label": "Diagram",
        "diagram_link":  "Open interactive version — drag, zoom, and click connections in your browser.",
        "how_to_use_heading": "How to Use This Document",
        "how_to_use_body": """This document is the single source of truth for this project.
It is generated automatically from the `docs/` folder and updated whenever a module completes.

**Who should read what:**

| Section | Audience | Purpose |
|---|---|---|
| Business | Everyone | Understand the problem being solved and the business rules |
| Requirements | PM, Tech Lead | What the system must do |
| Architecture | Engineers, Tech Lead | How the system is structured and deployed |
| Specifications | Engineers | Schema, API contracts, permissions, logging |
| Flows | Engineers | Code-level execution flows per module |
| Project Status | Tech Lead | What has been built and how code is organized |

**Diagrams:** Static images are embedded in each section.
Click "Open interactive version" to open the live draggable/zoomable version in your browser.

**To regenerate this PDF:**
```
python3 docs/script/generators/build_pdf.py docs --lang en -o docs/project-documentation-en.pdf
```
""",
        "sections": {
            "introduction":   "1. Introduction",
            "plan":           "2. Plan",
            "design":         "3. Design",
            "build":          "4. Build",
            "test":           "5. Test",
            "deployment":     "6. Deployment",
            # legacy keys kept for backward compatibility
            "requirements":   "1. Introduction",
            "specifications": "3. Design",
            "architecture":   "3. Design",
            "business":       "1. Introduction",
            "flows":          "4. Build",
            "project":        "4. Build",
        },
    },
    "zh": {
        "pdf_title":     "專案文件",
        "toc_heading":   "目錄",
        "diagram_label": "圖表",
        "diagram_link":  "開啟互動版本 — 可在瀏覽器中拖曳、縮放並點擊連線。",
        "how_to_use_heading": "如何使用本文件",
        "how_to_use_body": """本文件是專案的唯一事實來源，從 `docs/` 資料夾自動生成，每次模組完成時更新。

**各區塊的目標讀者：**

| 區塊 | 讀者 | 用途 |
|---|---|---|
| Business | 所有人 | 理解系統解決的業務問題與業務規則 |
| Requirements | PM、技術負責人 | 系統必須做什麼 |
| Architecture | 工程師、技術負責人 | 系統如何組成與部署 |
| Specifications | 工程師 | Schema、API 合約、權限、日誌規則 |
| Flows | 工程師 | 各模組的程式碼層級執行流程 |
| Project Status | 技術負責人 | 已完成的內容與程式碼組織方式 |

**圖表：** 靜態圖片已嵌入各區塊，點擊「開啟互動版本」可在瀏覽器中查看可拖曳/縮放的版本。

**重新生成 PDF：**
```
python3 docs/script/generators/build_pdf.py docs-zh --lang zh -o docs/project-documentation-zh.pdf
```
""",
        "sections": {
            "introduction":   "一、系統介紹",
            "plan":           "二、開發計畫",
            "design":         "三、系統設計",
            "build":          "四、建構實作",
            "test":           "五、測試",
            "deployment":     "六、部署",
            # legacy keys kept for backward compatibility
            "requirements":   "一、系統介紹",
            "specifications": "三、系統設計",
            "architecture":   "三、系統設計",
            "business":       "一、系統介紹",
            "flows":          "四、建構實作",
            "project":        "四、建構實作",
        },
    },
}

CSS_FONT_EN = "'Segoe UI', Arial, sans-serif"
CSS_FONT_ZH = "'Noto Sans CJK TC', 'Noto Sans TC', 'Microsoft JhengHei', 'Segoe UI', Arial, sans-serif"


SPEC_SECTIONS = {"introduction", "design", "build", "deployment"}

def find_allowed_files(docs_dir, strings, project_type=None, content="full"):
    """Return (rel, abs_path, section_label) for every allowlisted file that exists
    and applies to the given project_type. log-*.md files are intentionally excluded.

    project_type: frozenset of type strings (supports hybrid projects, e.g. {"data-pipeline","web-app"}),
                  or None to include all entries regardless of type (backward-compatible default).
    content: "full" (default) — all chapters; "spec" — Introduction, Design, Build, Deployment only.
    """
    result = []
    seen = set()

    for section_key, rel, types in PDF_ALLOWLIST:
        if content == "spec" and section_key not in SPEC_SECTIONS:
            continue
        if project_type is not None and not (project_type & types):
            continue
        abs_path = os.path.join(docs_dir, rel)
        section_label = strings["sections"][section_key]
        if os.path.exists(abs_path):
            result.append((rel, abs_path, section_label))
            seen.add(rel)
        else:
            if project_type is not None:
                print(f"Warning: expected file not found for "
                      f"{'+'.join(sorted(project_type))}, skipping: {rel}")
            # silently skip files that don't exist when no project type is set

    def _should_scan(pattern):
        if project_type is None:
            return True
        return bool(project_type & AUTO_SCAN_TYPES.get(pattern, frozenset()))

    flows_label = strings["sections"]["build"]

    # Insert individual module-data-flow files RIGHT AFTER the module-data-flow.md index entry
    # so they appear within the Build chapter, not after Deployment.
    data_flow_idx = next(
        (i for i, (r, _, _) in enumerate(result) if r == "modules/module-data-flow.md"),
        len(result),
    )
    insert_pos = data_flow_idx + 1
    if _should_scan("modules/*/*-module-data-flow.md"):
        for path in sorted(glob.glob(os.path.join(docs_dir, "modules", "*", "*-module-data-flow.md"))):
            rel = os.path.relpath(path, docs_dir)
            if rel not in seen:
                result.insert(insert_pos, (rel, path, flows_label))
                seen.add(rel)
                insert_pos += 1

    # Insert individual flow files RIGHT AFTER the module-flow.md index entry.
    flow_idx = next(
        (i for i, (r, _, _) in enumerate(result) if r == "modules/module-flow.md"),
        len(result),
    )
    insert_pos = flow_idx + 1
    if _should_scan("modules/*/*-flow.md"):
        for path in sorted(glob.glob(os.path.join(docs_dir, "modules", "*", "*-flow.md"))):
            rel = os.path.relpath(path, docs_dir)
            if rel not in seen:
                result.insert(insert_pos, (rel, path, flows_label))
                seen.add(rel)
                insert_pos += 1

    business_label = strings["sections"]["introduction"]
    if _should_scan("business/*-process.md"):
        for path in sorted(glob.glob(os.path.join(docs_dir, "business", "*-process.md"))):
            rel = os.path.relpath(path, docs_dir)
            if rel not in seen:
                for idx, (r, _, _) in enumerate(result):
                    if r == "business/business-process.md":
                        result.insert(idx + 1, (rel, path, business_label))
                        seen.add(rel)
                        break

    if _should_scan("business/*-object.md"):
        for path in sorted(glob.glob(os.path.join(docs_dir, "business", "*-object.md"))):
            rel = os.path.relpath(path, docs_dir)
            if rel not in seen:
                for idx, (r, _, _) in enumerate(result):
                    if r == "business/business-objects.md":
                        result.insert(idx + 1, (rel, path, business_label))
                        seen.add(rel)
                        break

    design_label = strings["sections"]["design"]
    if _should_scan("specs/prompts/*-prompt.md"):
        for path in sorted(glob.glob(os.path.join(docs_dir, "specs", "prompts", "*-prompt.md"))):
            rel = os.path.relpath(path, docs_dir)
            if rel not in seen:
                for idx, (r, _, _) in enumerate(result):
                    if r == "specs/prompt-library.md":
                        result.insert(idx + 1, (rel, path, design_label))
                        seen.add(rel)
                        break

    # Renumber chapters sequentially (1, 2, 3 …) based on appearance order.
    # This prevents gaps like 1 → 3 → 4 → 6 when spec mode skips chapters.
    seen_labels: list[str] = []
    for _, _, lbl in result:
        if lbl not in seen_labels:
            seen_labels.append(lbl)
    label_map: dict[str, str] = {}
    for i, lbl in enumerate(seen_labels, 1):
        base = re.sub(r"^\d+\.\s+|^[一二三四五六七八九十]+[、.]\s*", "", lbl)
        label_map[lbl] = f"{i}. {base}"
    result = [(rel, abs_path, label_map[lbl]) for rel, abs_path, lbl in result]

    return result


def render_plantuml_block(puml_text, out_svg_path):
    """Render a PlantUML block to SVG using plantuml.jar.
    Returns True on success, False on failure."""
    if not os.path.exists(PLANTUML_JAR):
        print(f"Warning: plantuml.jar not found at {PLANTUML_JAR}")
        print("  Set PLANTUML_JAR env var or place plantuml.jar next to build_pdf.py")
        return False
    with tempfile.NamedTemporaryFile(suffix='.puml', mode='w', delete=False, encoding='utf-8') as f:
        f.write(puml_text)
        tmp_puml = f.name
    try:
        out_svg_dir = os.path.dirname(os.path.abspath(out_svg_path))
        cfg_path = os.path.join(os.path.dirname(PLANTUML_JAR), 'plantuml.cfg')
        cmd = ['java', '-Dfile.encoding=UTF-8', '-jar', PLANTUML_JAR, '-tsvg', '-o', out_svg_dir]
        if os.path.exists(cfg_path):
            cmd += ['-config', cfg_path]
        cmd.append(tmp_puml)
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
        # PlantUML outputs SVG to out_svg_dir using the input filename's stem
        # e.g. /tmp/tmpXXXX.puml → out_svg_dir/tmpXXXX.svg
        tmp_svg = os.path.join(out_svg_dir, os.path.splitext(os.path.basename(tmp_puml))[0] + '.svg')
        if os.path.exists(tmp_svg):
            shutil.move(tmp_svg, out_svg_path)
            return True
        if result.returncode != 0:
            print(f"PlantUML error: {result.stderr[:200]}")
        return False
    except subprocess.TimeoutExpired:
        print("PlantUML render timed out")
        return False
    except FileNotFoundError:
        print("Java not found — install Java to render PlantUML diagrams")
        return False
    finally:
        os.unlink(tmp_puml)


def extract_plantuml_from_file(md_path, svg_cache_dir):
    """Extract all ```plantuml blocks from a markdown file and render them to SVG.
    Returns dict: {diagram_key: svg_path}"""
    with open(md_path, 'r', encoding='utf-8') as f:
        md_text = f.read()

    pairs = {}
    base = os.path.splitext(os.path.basename(md_path))[0]
    blocks = list(re.finditer(r'```plantuml\n([\s\S]*?)```', md_text))

    for idx, m in enumerate(blocks):
        puml_text = m.group(1).strip()
        suffix = '' if len(blocks) == 1 else f'-{idx}'
        key = f'{base}{suffix}'
        svg_path = os.path.join(svg_cache_dir, f'{key}.svg')
        pairs[key] = {'svg': svg_path, 'puml': puml_text, 'md': md_path}

    return pairs


def find_plantuml_diagrams(docs_dir, png_cache_dir, project_type=None, content="full"):
    """Scan all allowlisted markdown files for ```plantuml blocks.
    Renders each block to SVG (with mtime-based caching).
    Returns dict: {diagram_key: {svg, md}}"""
    svg_cache_dir = os.path.join(png_cache_dir, 'plantuml_svg')
    os.makedirs(svg_cache_dir, exist_ok=True)

    all_pairs = {}
    # Collect md files from allowlist + auto-scanned patterns
    md_files = set()
    for section_key, rel, types in PDF_ALLOWLIST:
        if content == "spec" and section_key not in SPEC_SECTIONS:
            continue
        if project_type is not None and not (project_type & types):
            continue
        abs_path = os.path.join(docs_dir, rel)
        if os.path.exists(abs_path):
            md_files.add(abs_path)
    # Also scan auto-included files not in the static allowlist
    for pattern, types in AUTO_SCAN_TYPES.items():
        if project_type is not None and not (project_type & types):
            continue
        for p in glob.glob(os.path.join(docs_dir, pattern)):
            md_files.add(p)

    for md_path in md_files:
        pairs = extract_plantuml_from_file(md_path, svg_cache_dir)
        for key, info in pairs.items():
            svg_path = info['svg']
            puml_text = info['puml']
            md_mtime  = os.path.getmtime(md_path)
            svg_mtime = os.path.getmtime(svg_path) if os.path.exists(svg_path) else -1
            if not os.path.exists(svg_path) or md_mtime > svg_mtime:
                print(f"  Rendering {key}...")
                render_plantuml_block(puml_text, svg_path)
            if os.path.exists(svg_path):
                all_pairs[key] = {'svg': svg_path, 'html': None, 'md': md_path}

    return all_pairs


def find_html_svg_pairs(docs_dir):
    """Find .html files that have a matching .svg (legacy — kept for schema_to_html.py ERD)."""
    pairs = {}
    for html_path in glob.glob(os.path.join(docs_dir, "**", "*.html"), recursive=True):
        svg_path = os.path.splitext(html_path)[0] + ".svg"
        if os.path.exists(svg_path):
            key = os.path.splitext(os.path.basename(html_path))[0]
            pairs[key] = {"html": html_path, "svg": svg_path}
    return pairs


def svg_to_png(svg_path, out_path, max_width=1400, max_height=900):
    """Convert SVG to PNG, scaling to fit within max_width x max_height."""
    tree = ET.parse(svg_path)
    root = tree.getroot()
    vb = root.get('viewBox', '')
    if vb:
        parts = vb.split()
        svg_w = float(parts[2])
        svg_h = float(parts[3])
        scale_w = max_width / svg_w
        scale_h = max_height / svg_h
        scale = min(scale_w, scale_h)
        out_w = int(svg_w * scale)
        out_h = int(svg_h * scale)
    else:
        out_w = max_width
        out_h = None
    cairosvg.svg2png(url=svg_path, write_to=out_path,
                     output_width=out_w, output_height=out_h)
    return out_path


def inject_plantuml_blocks(md_text, rel, docs_dir, html_svg_pairs, png_cache_dir):
    """Replace ```plantuml blocks in markdown with embedded PNG images."""
    base = os.path.splitext(os.path.basename(rel))[0]

    def replace_block(m):
        puml_text = m.group(1).strip()
        # Find matching pre-rendered SVG
        svg_cache_dir = os.path.join(png_cache_dir, 'plantuml_svg')
        # Try to find the svg by scanning rendered pairs
        for key, pair in html_svg_pairs.items():
            if pair.get('md') and os.path.basename(pair['md']) == os.path.basename(rel):
                svg_path = pair['svg']
                if os.path.exists(svg_path):
                    png_name = os.path.splitext(os.path.basename(svg_path))[0] + '.png'
                    png_path = os.path.join(png_cache_dir, png_name)
                    svg_mtime  = os.path.getmtime(svg_path)
                    png_mtime  = os.path.getmtime(png_path) if os.path.exists(png_path) else -1
                    if not os.path.exists(png_path) or svg_mtime > png_mtime:
                        svg_to_png(svg_path, png_path)
                    if os.path.exists(png_path):
                        png_rel = os.path.relpath(png_path, docs_dir)
                        return '![](' + png_rel + ')\n'
        return ''  # fallback: remove the block if no SVG found

    return re.sub(r'```plantuml([\s\S]*?)```', replace_block, md_text)


def inject_diagrams(md_text, rel, docs_dir, html_svg_pairs, png_cache_dir, strings):
    """Inject a rendered PNG + clickable link for diagrams whose target doc matches rel.

    Fixed targets come from DIAGRAM_TARGETS.
    Dynamic targets: a key ending in '-module-data-flow-class' maps to the
    corresponding '[module]-module-data-flow.md' file in flows/.
    """
    for key, pair in html_svg_pairs.items():
        # Resolve target: fixed mapping first, then dynamic module-data-flow-class pattern
        raw_target = DIAGRAM_TARGETS.get(key)
        # raw_target can be:
        #   str  → inject into that one doc
        #   list → inject into each listed doc (diagram appears in multiple sections)
        #   None → resolved dynamically below
        if isinstance(raw_target, list):
            # Only inject into the current doc if it's one of the listed targets
            if rel not in raw_target:
                continue
            target = rel
        elif raw_target is not None:
            target = raw_target
        else:
            target = None
        if target is None:
            # Dynamic: order-module-data-flow-class → modules/order/order-module-data-flow.md
            m = re.match(r'^(.+)-class$', key)
            if m:
                base = m.group(1)  # e.g. order-module-data-flow
                # Extract module name: order-module-data-flow -> order
                module_name = base.replace('-module-data-flow', '')
                target = f"modules/{module_name}/{base}.md"

            # Dynamic: order-flow-sequence → modules/order/order-flow.md
            m2 = re.match(r'^(.+)-sequence$', key)
            if m2:
                base = m2.group(1)  # e.g. order-flow
                module_name = base.replace('-flow', '')
                target = f"modules/{module_name}/{base}.md"

            # Dynamic: order-flow-activity → modules/order/order-flow.md
            # Dynamic: order-create-process-activity → business/order-create-process.md
            m3 = re.match(r'^(.+)-activity$', key)
            if m3:
                base = m3.group(1)
                if base.endswith('-flow'):
                    module_name = base.replace('-flow', '')
                    target = f"modules/{module_name}/{base}.md"
                elif base.endswith('-process'):
                    target = f"business/{base}.md"

            # Dynamic: order-object-state → business/order-object.md
            m4 = re.match(r'^(.+)-state$', key)
            if m4:
                base = m4.group(1)
                if base.endswith('-object'):
                    target = f"business/{base}.md"
                elif base == 'data-model':
                    target = 'specs/data-model.md'

        if target != rel:
            continue

        png_name = f"{key}.png"
        png_path = os.path.join(png_cache_dir, png_name)
        # Regenerate PNG if it does not exist OR if the source SVG is newer than the cache
        svg_mtime = os.path.getmtime(pair["svg"]) if os.path.exists(pair["svg"]) else 0
        png_mtime = os.path.getmtime(png_path)    if os.path.exists(png_path)   else -1
        if not os.path.exists(png_path) or svg_mtime > png_mtime:
            svg_to_png(pair["svg"], png_path)

        png_rel = os.path.relpath(png_path, docs_dir)
        # PlantUML-generated pairs have html=None — skip interactive link
        html_rel = os.path.relpath(pair["html"], docs_dir) if pair.get("html") else None

        # Check if image is tall (height > width) — use full-page display
        img = Image.open(png_path)
        img_w, img_h = img.size
        is_tall = img_h > img_w * 1.5

        link_html = (
                f'<p style="margin-top:8px;"><a href="{html_rel}" style="color:#3182CE;">'
                f'🔗 {strings["diagram_link"]}</a></p>'
            ) if html_rel else ""
        link_md = (
                f"> 🔗 [{strings['diagram_link']}]({html_rel})\n\n"
            ) if html_rel else "\n\n"
        if is_tall:
            block = (
                f'\n\n<div style="page-break-before: always; text-align: center; padding: 24px;">'
                f'<p style="font-weight:bold; color:#2D3748; margin-bottom:8px;">'
                f'{strings["diagram_label"]}: {key}</p>'
                f'<img src="{png_rel}" style="max-width:90%; max-height:90vh; object-fit:contain;"/>'
                f'{link_html}</div>\n\n'
            )
        else:
            block = (
                f"\n\n> **{strings['diagram_label']}: {key}**\n"
                f">\n"
                f"> ![{key} diagram]({png_rel})\n"
                f">\n"
                f"{link_md}"
            )
        # If the doc contains a placement marker <!-- diagram: KEY -->, insert there.
        # Otherwise append to end of document.
        marker = f'<!-- diagram: {key} -->'
        if marker in md_text:
            md_text = md_text.replace(marker, block, 1)
        else:
            md_text += block

    return md_text


def filter_sections(md_text, keep_headings):
    """
    Keep only the specified ## sections (and their content) from a markdown file.
    Everything else — including the file's H1 title and any other sections — is removed.
    keep_headings: list of exact heading strings, e.g. ["## Module Flow Files"]
    """
    lines = md_text.splitlines(keepends=True)
    result = []
    inside_kept = False
    current_level = None

    for line in lines:
        stripped = line.rstrip()

        # Detect headings
        heading_match = re.match(r'^(#{1,6})\s+(.+)$', stripped)
        if heading_match:
            level = len(heading_match.group(1))
            full_heading = stripped

            # Check if this heading is one we want to keep
            if full_heading in keep_headings:
                inside_kept = True
                current_level = level
                result.append(line)
                continue

            # If we hit a heading of same or higher level, stop keeping
            if inside_kept and level <= current_level:
                inside_kept = False
                current_level = None
            # Sub-headings inside a kept section are kept automatically
            # (they have higher level number = lower hierarchy)

        if inside_kept:
            result.append(line)

    return ''.join(result).strip()



def clean_for_pdf(md_text):
    """
    Strip AI-instruction content from markdown before rendering to PDF.

    Removes:
    1. HTML comments <!-- ... -->
    2. Table rows where every cell is a placeholder ([...] or empty)
    3. Top-level sections whose heading is a placeholder (e.g. # [Process Name])
       — these are template format-example sections, not real content
    """

    # 1. Remove HTML comments (single-line and multi-line)
    md_text = re.sub(r'<!--.*?-->', '', md_text, flags=re.DOTALL)

    # 2. Remove placeholder table rows — every cell matches [...] or is blank/dash
    placeholder_cell = re.compile(r'^\s*\[.*?\]\s*$|^\s*—\s*$|^\s*-\s*$|^\s*$')

    def is_placeholder_row(line):
        if not line.startswith('|'):
            return False
        cells = [c.strip() for c in line.strip().strip('|').split('|')]
        return bool(cells) and all(placeholder_cell.match(c) for c in cells)

    lines = md_text.splitlines()
    md_text = '\n'.join(line for line in lines if not is_placeholder_row(line))

    # 3. Remove sections whose heading is a pure placeholder: # [...] or ## [...]
    def remove_placeholder_sections(text):
        pattern = re.compile(r'^(#{1,3})\s+\[.*?\]\s*$', re.MULTILINE)
        result = []
        pos = 0
        for m in pattern.finditer(text):
            result.append(text[pos:m.start()])
            level = len(m.group(1))
            # Skip until next heading of same or higher level
            next_m = re.search(r'^#{1,' + str(level) + r'}\s+', text[m.end():], re.MULTILINE)
            pos = m.end() + next_m.start() if next_m else len(text)
        result.append(text[pos:])
        return ''.join(result)

    md_text = remove_placeholder_sections(md_text)

    # Clean up excessive blank lines
    md_text = re.sub(r'\n{3,}', '\n\n', md_text)

    return md_text


def build_merged_markdown(docs_dir, html_svg_pairs, png_cache_dir, strings, project_type=None, content="full"):
    files = find_allowed_files(docs_dir, strings, project_type, content)
    if not files:
        print("No files to include — check PDF_ALLOWLIST in build_pdf.py")
        sys.exit(1)

    parts = [f"# {strings['pdf_title']}\n"]

    # How to use page
    parts.append(f"\n\n# {strings['how_to_use_heading']}\n\n{strings['how_to_use_body']}\n")

    parts.append(f"## {strings['toc_heading']}\n")
    toc_lines = []
    body_parts = []

    current_section = None
    for rel, abs_path, section_label in files:
        if section_label != current_section:
            body_parts.append(f"\n\n# {section_label}\n")
            toc_lines.append(f"- **{section_label}**")
            current_section = section_label

        with open(abs_path, "r", encoding="utf-8") as f:
            content = f.read()

        # Apply per-file section filter if defined
        if rel in PDF_SECTION_FILTER:
            content = filter_sections(content, PDF_SECTION_FILTER[rel])
        content = clean_for_pdf(content)
        # Replace ```plantuml blocks with rendered PNG images
        content = inject_plantuml_blocks(content, rel, docs_dir, html_svg_pairs, png_cache_dir)
        # Also inject legacy <!-- diagram: KEY --> markers (e.g. schema ERD)
        content = inject_diagrams(content, rel, docs_dir, html_svg_pairs, png_cache_dir, strings)

        # Use the first # H1 heading from the file as the title; fall back to filename.
        h1_match = re.search(r"^#\s+(.+)$", content, re.MULTILINE)
        title = h1_match.group(1).strip() if h1_match else os.path.splitext(os.path.basename(rel))[0]
        # Strip the leading H1 from the file content — the section wrapper below already provides it.
        content_body = re.sub(r"^#\s+.+\n?", "", content, count=1)
        toc_lines.append(f"  - {title}")
        body_parts.append(f"\n\n## {title}\n\n{content_body}")

    parts.append("\n".join(toc_lines))
    parts.extend(body_parts)
    return "\n".join(parts)


def build_css(lang):
    font = CSS_FONT_ZH if lang == "zh" else CSS_FONT_EN
    return f"""
@page {{
    size: A4;
    margin: 2cm;
    @bottom-center {{
        content: counter(page) " / " counter(pages);
        font-size: 9px;
        color: #888;
    }}
}}
body {{
    font-family: {font};
    font-size: 10.5pt;
    line-height: 1.6;
    color: #1a1a1a;
}}
h1 {{
    font-size: 20pt;
    border-bottom: 2px solid #2D3748;
    padding-bottom: 6px;
    page-break-before: always;
}}
h1:first-of-type {{ page-break-before: avoid; }}
h2 {{
    font-size: 14pt;
    color: #2D3748;
    margin-top: 24px;
    border-bottom: 1px solid #ddd;
    padding-bottom: 4px;
}}
h3 {{ font-size: 12pt; color: #2B6CB0; }}
code {{
    background: #f0f0f0;
    padding: 1px 5px;
    border-radius: 3px;
    font-size: 9pt;
}}
pre {{
    background: #1A202C;
    color: #E2E8F0;
    padding: 10px;
    border-radius: 6px;
    font-size: 8.5pt;
    overflow-x: auto;
    white-space: pre-wrap;
}}
pre code {{ background: none; color: inherit; padding: 0; }}
table {{
    border-collapse: collapse;
    width: 100%;
    font-size: 9pt;
    margin: 12px 0;
}}
th, td {{
    border: 1px solid #ccc;
    padding: 4px 8px;
    text-align: left;
    word-break: break-word;
    overflow-wrap: break-word;
}}
th {{ background: #2D3748; color: white; }}
blockquote {{
    border-left: 4px solid #3182CE;
    margin: 12px 0;
    padding: 8px 16px;
    background: #EBF8FF;
}}
blockquote img {{
    max-width: 100%;
    max-height: 500px;
    object-fit: contain;
    display: block;
}}
img {{ max-width: 100%; }}
a {{ color: #3182CE; text-decoration: none; }}
"""


VALID_PROJECT_TYPES = {
    "web-app", "cli-tool", "library", "data-pipeline",
    "ml-pipeline", "microservices", "llm-app", "iac", "mobile-app",
}

def parse_args():
    parser = argparse.ArgumentParser(
        description="Merge approved docs/ content into a single PDF.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "docs_dir",
        nargs="?",
        default="docs",
        help="Path to the docs directory (default: docs)",
    )
    parser.add_argument(
        "-o",
        dest="output_path",
        metavar="OUTPUT",
        help="Output PDF path (default: <docs_dir>/project-{documentation|spec}-<lang>.pdf)",
    )
    parser.add_argument(
        "--lang",
        default="en",
        choices=list(STRINGS),
        help="Section labels and UI text language (default: en)",
    )
    parser.add_argument(
        "--project-type",
        metavar="TYPE",
        help=(
            "Comma-separated project type(s) to filter the PDF. "
            f"Valid values: {', '.join(sorted(VALID_PROJECT_TYPES))}"
        ),
    )
    parser.add_argument(
        "--content",
        default="full",
        choices=["full", "spec"],
        help="full — all chapters; spec — Introduction, Design, Build, Deployment only (default: full)",
    )

    args = parser.parse_args()

    project_type = None
    if args.project_type is not None:
        project_type = frozenset(t.strip() for t in args.project_type.split(","))
        invalid = project_type - VALID_PROJECT_TYPES
        if invalid:
            parser.error(
                f"Unsupported project type(s): {', '.join(sorted(invalid))}. "
                f"Available: {', '.join(sorted(VALID_PROJECT_TYPES))}"
            )

    output_path = args.output_path
    if not output_path:
        suffix = "spec" if args.content == "spec" else "documentation"
        output_path = os.path.join(args.docs_dir, f"project-{suffix}-{args.lang}.pdf")

    return args.docs_dir, output_path, args.lang, project_type, args.content


def main():
    docs_dir, output_path, lang, project_type, content = parse_args()
    strings = STRINGS[lang]

    if not os.path.isdir(docs_dir):
        print(f"Directory not found: {docs_dir}")
        sys.exit(1)

    png_cache_dir = os.path.join(docs_dir, ".pdf_build_cache")
    if os.path.isdir(png_cache_dir):
        shutil.rmtree(png_cache_dir)
    os.makedirs(png_cache_dir, exist_ok=True)

    if project_type:
        print(f"Project type: {' + '.join(sorted(project_type))}")
    if content != "full":
        print(f"Content mode: {content}")

    # Legacy: find manually-generated SVG/HTML pairs (e.g. schema ERD)
    html_svg_pairs = find_html_svg_pairs(docs_dir)
    # New: extract and render all ```plantuml blocks from markdown files
    plantuml_pairs = find_plantuml_diagrams(docs_dir, png_cache_dir, project_type, content)
    html_svg_pairs.update(plantuml_pairs)
    print(f"Found {len(html_svg_pairs)} diagram(s): {list(html_svg_pairs.keys())}")
    print(f"Language: {lang}")

    merged_md = build_merged_markdown(docs_dir, html_svg_pairs, png_cache_dir, strings,
                                      project_type=project_type, content=content)

    md_html = markdown.markdown(
        merged_md,
        extensions=["tables", "fenced_code", "toc", "nl2br"]
    )

    full_html = f"<html><head><meta charset='utf-8'></head><body>{md_html}</body></html>"

    HTML(string=full_html, base_url=docs_dir).write_pdf(
        output_path,
        stylesheets=[CSS(string=build_css(lang))]
    )

    print(f"Done: {output_path}")


if __name__ == "__main__":
    main()
