#!/usr/bin/env python3
"""generate_sprint_checklist.py — Generate the Document Update Checklist section for sprint-sync.md.

Reads document-registry.yaml and emits the checklist rows in the [Types: ...] format
used by sprint-sync.md. Run at sprint end or whenever the registry changes.

Usage:
  python3 generate_sprint_checklist.py
  python3 generate_sprint_checklist.py --registry path/to/document-registry.yaml
  python3 generate_sprint_checklist.py --output sprint-checklist-section.md
"""

import argparse
import sys
from pathlib import Path

_validators_dir = Path(__file__).resolve().parent.parent / 'validators'
sys.path.insert(0, str(_validators_dir))

try:
    from _registry import load_registry, VALID_TYPES
except ImportError:
    print("❌  _registry.py not found. Run from the project_starter_v5 repo root.", file=sys.stderr)
    sys.exit(1)


def _types_tag(required: list[str], optional: list[str]) -> str:
    if set(required) == set(VALID_TYPES):
        return "[Types: All]"
    parts = [f"{t}" for t in VALID_TYPES if t in required]
    opt_parts = [f"{t} (optional)" for t in VALID_TYPES if t in optional]
    combined = parts + opt_parts
    return f"[Types: {', '.join(combined)}]" if combined else "[Types: None]"


def generate_checklist(registry: dict) -> str:
    lines = [
        "## Document Update Checklist",
        "",
        "<!-- Generated by generate_sprint_checklist.py — do not edit this section manually. -->",
        "<!-- Re-run the script when document-registry.yaml changes. -->",
        "",
        "| # | Document | Types | Update trigger |",
        "|---|---|---|---|",
    ]
    for i, (name, meta) in enumerate(registry.items(), 1):
        doc_md = name if name.endswith('.md') else f'{name}.md'
        required = meta.get('required_for', [])
        optional = meta.get('optional_for', [])
        trigger = meta.get('update_trigger', '—')
        tag = _types_tag(required, optional)
        lines.append(f"| {i} | `{doc_md}` | {tag} | {trigger} |")

    lines.append("")
    return '\n'.join(lines)


def _find_registry(cli_path: str | None) -> Path:
    if cli_path:
        return Path(cli_path)
    candidates = [
        Path.cwd() / 'document-registry.yaml',
        Path(__file__).resolve().parent.parent.parent / 'document-registry.yaml',
    ]
    for p in candidates:
        if p.exists():
            return p
    raise FileNotFoundError(
        'document-registry.yaml not found. '
        f'Searched: {[str(c) for c in candidates]}'
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate the Document Update Checklist section for sprint-sync.md."
    )
    parser.add_argument('--registry', metavar='PATH',
                        help='Path to document-registry.yaml (auto-discovered by default)')
    parser.add_argument('--output', '-o', metavar='FILE',
                        help='Write output to FILE instead of stdout')
    args = parser.parse_args()

    try:
        registry_path = _find_registry(args.registry)
    except FileNotFoundError as e:
        print(f"❌  {e}", file=sys.stderr)
        sys.exit(2)

    registry = load_registry(registry_path)
    checklist = generate_checklist(registry)

    if args.output:
        Path(args.output).write_text(checklist, encoding='utf-8')
        print(f"✅  Checklist written to {args.output}")
    else:
        print(checklist)


if __name__ == '__main__':
    main()
