#!/usr/bin/env python3
"""
propose_framework_fix.py — open a PR on project_starter_v5 for a framework template gap.

Creates a branch, appends a placeholder section to the relevant template, and opens a PR
via `gh pr create`. The PR contains no project-specific content — a human reviews it before
merging.

Usage:
  python3 templates/script/propose_framework_fix.py \\
      --type web-app \\
      --document specs/research.md \\
      --gap-description "Error Handling"

  python3 templates/script/propose_framework_fix.py \\
      --type data-pipeline \\
      --document specs/pipeline-contract.md \\
      --gap-description "Stage Contracts" \\
      --dry-run
"""

import argparse
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

# Path inside the framework repo where templates live
TEMPLATES_SUBPATH = "templates"


def slugify(text: str, max_len: int = 40) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")[:max_len]


def build_branch_name(project_type: str, document: str, gap_description: str) -> str:
    doc_slug = slugify(Path(document).stem)
    gap_slug = slugify(gap_description)
    branch = f"auto-fix/{slugify(project_type)}/{doc_slug}-{gap_slug}"
    return branch[:79]  # stay within git branch name limits


def generate_fix_text(project_type: str, document: str, gap_description: str) -> str:
    """Return the text to append to the template for this gap."""
    return (
        f"\n---\n\n"
        f"## {gap_description}\n\n"
        f"<!-- Auto-generated placeholder: {project_type} / {document} -->\n"
        f"<!-- Describe the expected content for this section. -->\n"
        f"<!-- Example: [replace this comment with a concrete example] -->\n"
    )


def run(cmd: list[str], cwd: Path | None = None, check: bool = False) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, check=check)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Propose a framework fix PR for a missing template section."
    )
    parser.add_argument("--type", required=True, help="Project type (e.g. web-app)")
    parser.add_argument(
        "--document", required=True,
        help="Template-relative path (e.g. specs/research.md)"
    )
    parser.add_argument(
        "--gap-description", required=True,
        help="Short name for the missing section (e.g. 'Error Handling')"
    )
    parser.add_argument(
        "--framework-repo", default=os.environ.get("PROJECT_STARTER_FRAMEWORK_REPO"),
        help="GitHub repo to open the PR on (owner/repo). "
             "Defaults to $PROJECT_STARTER_FRAMEWORK_REPO."
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Print what would happen without cloning, committing, or creating a PR"
    )
    args = parser.parse_args()

    if not args.framework_repo:
        print(
            "❌ PROJECT_STARTER_FRAMEWORK_REPO is not set.\n"
            "   Export it before running:\n"
            "     export PROJECT_STARTER_FRAMEWORK_REPO=your-org/your-repo",
            file=sys.stderr,
        )
        return 1

    branch = build_branch_name(args.type, args.document, args.gap_description)
    template_repo_path = f"{TEMPLATES_SUBPATH}/{args.document}"

    pr_title = f"[Auto-fix] {args.type} / {args.document}: add {args.gap_description} section"
    pr_body = (
        f"## Detected gap\n\n"
        f"`{args.type}` projects using `{args.document}` have no template guidance "
        f"for: **{args.gap_description}**.\n\n"
        f"## Fix applied\n\n"
        f"Added a placeholder `## {args.gap_description}` section with guidance comments "
        f"to the template. Review and fill in concrete guidance before merging.\n\n"
        f"---\n"
        f"_Auto-generated by `diagnose_spec.py`. No project-specific content included._"
    )

    if args.dry_run:
        print(f"[dry-run] branch:   {branch}")
        print(f"[dry-run] template: {template_repo_path}")
        print(f"[dry-run] PR title: {pr_title}")
        return 0

    with tempfile.TemporaryDirectory(prefix="ps5-fix-") as tmpdir:
        clone_dir = Path(tmpdir) / "ps5"

        # Clone the framework repo (shallow clone is fine)
        result = run(["gh", "repo", "clone", args.framework_repo, str(clone_dir), "--", "--depth=1"], check=False)
        if result.returncode != 0:
            print(f"❌ Clone failed: {result.stderr.strip()}", file=sys.stderr)
            return 1

        # Create branch
        result = run(["git", "checkout", "-b", branch], cwd=clone_dir, check=False)
        if result.returncode != 0:
            print(f"❌ Branch creation failed: {result.stderr.strip()}", file=sys.stderr)
            return 1

        # Locate and edit the template file
        template_path = clone_dir / template_repo_path
        if not template_path.exists():
            print(f"❌ Template not found in repo: {template_repo_path}", file=sys.stderr)
            return 1

        fix_text = generate_fix_text(args.type, args.document, args.gap_description)
        existing = template_path.read_text(encoding="utf-8")

        # Skip if the section already exists (idempotency guard)
        heading = f"## {args.gap_description}"
        if heading in existing:
            print(f"⚠️  Section '{heading}' already exists in {args.document} — skipping PR.")
            return 0

        template_path.write_text(existing.rstrip() + "\n" + fix_text, encoding="utf-8")

        # Commit
        rel_path = str(template_path.relative_to(clone_dir))
        run(["git", "add", rel_path], cwd=clone_dir)
        commit_msg = (
            f"[auto-fix] {args.type}/{args.document}: "
            f"add {args.gap_description} section placeholder"
        )
        result = run(["git", "commit", "-m", commit_msg], cwd=clone_dir, check=False)
        if result.returncode != 0:
            print(f"❌ Commit failed: {result.stderr.strip()}", file=sys.stderr)
            return 1

        # Push branch
        result = run(["git", "push", "origin", branch], cwd=clone_dir, check=False)
        if result.returncode != 0:
            print(f"❌ Push failed: {result.stderr.strip()}", file=sys.stderr)
            return 1

        # Open PR
        result = run(
            ["gh", "pr", "create", "--title", pr_title, "--body", pr_body,
             "--repo", args.framework_repo],
            cwd=clone_dir, check=False,
        )
        if result.returncode == 0:
            pr_url = result.stdout.strip()
            print(f"✅ PR opened: {pr_url}")
            return 0
        else:
            print(f"❌ PR creation failed: {result.stderr.strip()}", file=sys.stderr)
            return 1


if __name__ == "__main__":
    sys.exit(main())
